Traceback (most recent call last):
  File "/home/pi/crons/spotify/main.py", line 3, in <module>
    print(error)
NameError: name 'error' is not defined
